#+title: Claim your Topic (Assigment)

* Read Before Starting
DEADLINE: <2026-02-11 Wed 12:00>
Claim your topic for the Informative Speech here. The topics can not be
repeated. First come, first serve.

1. Think of a topic that interests you but is also interesting to your peers.
   Verify whether it has already been claimed by a classmate.
   Why Abroad Students and Joseph has so much in common?
2. Ensure your topic is not too broad! Your speech should go beyond a
   surface-level overview and demonstrate thorough, in-depth research.
3. If someone else's topic appears similar to yours, be sure to review its
   description to ensure there is no overlap.
4. Start a new discussion by clicking the "Add discussion topic" button and use
   the title of your selected topic as the "Subject" of your post. Ensure your
   topic/subject is specific.
5. In the body of your post, include the following based on your current
   understanding of the topic:
   a. Specific purpose of your speech
   b. Thesis statement of your speech
   c. Brief overview of what you plan to discuss.

* Speech Research
** Introduction
*** Why did Joseph's Brother's Wanted to Kill Him?
The Bible itself doesn't present the exact reason of why Joseph is hated so much
by their brothers, however we can infer a few things from Joseph.
1. He was the favorite
   from Genesis 37:2 we know:
   Now Israel loved Joseph more than any of his other sons, because he had been
   born to him in his old age; and he made an ornate[a] robe for him. 4 When his
   brothers saw that their father loved him more than any of them, they hated
   him and could not speak a kind word to him.
   *But could someone be hated so much just because of this favoritism?*
2. He had dreams
   this is said in Genesis 37:3
   Joseph had a dream, and when he told it to his brothers, they hated him all
   the more.
   *Could he be a prophet? Why Him?*
3. He was loved, the favorite, and he thinks that he could administer them from
   a superior position.
   from Genesis 37:8
   His brothers said to him, “Do you intend to reign over us? Will you actually
   rule us?” And they hated him all the more because of his dream and what he
   had said.
   *Does he think he could be the administer of all of Israel things*
